import bipolar from '../assets/images/bipolar.png'
import dementia from '../assets/images/dementia.png'
import insomnia from '../assets/images/insomnia.png'
import schizo from '../assets/images/schizo.png'
import anxiety from '../assets/images/apprenhensive.png'
import stress from '../assets/images/fear.png'
import pfp1 from '../assets/images/pfp1.jpeg'
import pfp2 from '../assets/images/pfp2.jpeg'
import depression from '../assets/images/depression.png'
import lady from '../assets/images/girl.png'
import imgPost from '../assets/images/imgPost.jpeg'
import patient from '../assets/images/patient.png'
import doctor from '../assets/images/doctor.png'
import waving from '../assets/images/Waving.jpg'

export default { bipolar, dementia, insomnia, schizo, anxiety, stress, pfp1, pfp2, depression, lady, imgPost, patient, doctor, waving }